theme = "catppuccin"

[editor]
line-number = "absolute"
mouse = true
idle-timeout = 100

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)

[keys.insert]
#C-h = "move_char_left" 
#C-j = "move_char_down" 
#C-k = "move_char_up" 
#C-l = "move_char_right" 


