theme = "catppuccin"

[editor]
line-number = "absolute"
mouse = true
idle-timeout = 100

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
